"""Default settings for the Claude auth helper."""

DEFAULT_CLAUDE_URL = "https://claude.ai"
DEFAULT_PLAYWRIGHT_TMPDIR = "/tmp"
DEFAULT_SESSION_PREFIX = "claude-auth"
DEFAULT_URL_TIMEOUT_SECONDS = 120.0
DEFAULT_AUTH_BUTTON_TIMEOUT_SECONDS = 60.0
DEFAULT_AUTH_BUTTON_POLL_SECONDS = 1.0
DEFAULT_AUTH_COMPLETION_TIMEOUT_SECONDS = 120.0
DEFAULT_LOGIN_BROWSER_WIDTH = 1280
DEFAULT_LOGIN_BROWSER_HEIGHT = 1200
